name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            rust-all \
            cbindgen \
            pigz \
            python3-pip \
            nodejs \
            npm \
            libgtk-3-dev \
            libdbus-glib-1-dev \
            libxt-dev \
            libpulse-dev

      - name: Verify Rust installation
        run: |
          rustc --version
          cargo --version
          cbindgen --version

      - name: Build WayneWolf
        run: |
          cd WayneWolf
          make fetch
          make dir
          make bootstrap
          make setup-wasi
          make build

      - name: Test build
        run: |
          cd WayneWolf
          make package

          # Verify tarball was created
          if [ ! -f librewolf-*.tar.xz ]; then
            echo "Error: Build failed - no tarball created"
            exit 1
          fi

          echo "Build successful!"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: waynewolf-build-${{ github.sha }}
          path: WayneWolf/librewolf-*.tar.xz
          retention-days: 7

  test-installation:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: waynewolf-build-${{ github.sha }}
          path: .

      - name: Test installation script
        run: |
          # Move tarball to expected location
          mv librewolf-*.tar.xz .

          # Run installation
          ./install.sh

          # Verify installation
          if [ ! -f "$HOME/.local/bin/waynewolf" ]; then
            echo "Error: Installation failed - waynewolf binary not found"
            exit 1
          fi

          echo "Installation test successful!"
